### ISSUE TITLE
Compatibility with wxWidgets 3.0.2.0

### ISSUE THREAD

**Issue by remicollet** [jgmdev/phar-gui#2]
$  phar-gui 
     
     Strict standards: Declaration of PharGUI\Window::OnTreeSelChanged() should be compatible with PharFrameTemplate::OnTreeSelChanged($event) in /usr/share/phar-gui/lib/PharGUI/Window.php on line 925

**Comment by jgmdev** [comment]
I think it should be fixed now with commit 3d8220a3745d62281042bf66b1bdf70dfe0c3b4e I hope I didn't messed something else, since I had some uncommitted local changes and do not remember exactly what I was doing :D.

**Comment by remicollet** [comment]
Yes, seems ok now, thanks
